version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: advanced_databases
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: advanced_databases
    ports:
      - "1111:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
